call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.0005
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.001
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.002
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.003
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.005
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.007
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.01
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.05
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.1
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 0.5
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 2.0
call java -jar target/NetworkDemonstrator-1.0-SNAPSHOT-jar-with-dependencies.jar 3.0